# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  build:
    cmds:
      - snapcraft --use-lxd

  debug:
    cmds:
      - snapcraft --use-lxd --debug
  
  debug-shell:
    cmds:
      - snap run --shell afm-camp.maria-client

  clean:
    cmds:
      - snapcraft clean --use-lxd

  install:
    cmds:
      - snap install afm-camp_0.2* --devmode

  remove:
    cmds:
      - snap remove afm-camp

  upload-edge:
    cmds:
      - snapcraft upload --release=edge afm-camp_0.2*.snap

  upload-beta:
    cmds:
      - snapcraft upload --release=beta afm-camp_0.2*.snap

  upload-candidate:
    cmds:
      - snapcraft upload --release=candidate afm-camp_0.2*.snap

  upload-stable:
    cmds:
      - snapcraft upload --release=stable afm-camp_0.2*.snap
